version: "3.9"

services:
  api:
    build: .
    ports:
      - "2222:2222" # Expose API on localhost:2222
    environment:
      - NODE_ENV=production
      - PORT=2222
      - DATABASE_URL=postgresql://postgres:password@db:5432/playground
    depends_on:
      - db
    command: >
      sh -c "
      pnpm db:push &&
      pnpm db:seed &&
      pnpm start
      "

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432" # Expose PostgreSQL on localhost:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playground
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: # Named volume for PostgreSQL persistence
